### ISSUE TITLE
Compilation error in Android Studio 3.5

### ISSUE THREAD

**Issue by abhishekinexture** [atsushieno/fluidsynth-midi-service-j#17]
I am trying to build this project after cloning in Android Studio 3.5 but it gives me a compilation error:

![compilation error](https://user-images.githubusercontent.com/39045354/59344365-92f2b300-8d2b-11e9-8127-45e1eda647ab.png)

As per your description in the readme file for compiling fluidsynthjna, I have entered the following code to the terminal:

make prepare

But it gives me a folowing error:

make: *** No rule to make target 'prepare'.  Stop.

Do we need to modify any file of the project before the compilation process?

**Comment by atsushieno** [comment]
oh, that's my mistake; please try `make prepare-fluidsynth`

**Comment by atsushieno** [comment]
updated README.md to reflect ^.

**Comment by abhishekinexture** [comment]
After that, I got the following error while running `make` command:

Makefile:17: recipe for target '../external/JNAerator/jnaerator/target/jnaerator-0.13-SNAPSHOT-shaded.jar' failed
make: *** [../external/JNAerator/jnaerator/target/jnaerator-0.13-SNAPSHOT-shaded.jar] Error 1

**Comment by atsushieno** [comment]
There should be more contextful build log messages _above_ those lines.

**Comment by abhishekinexture** [comment]
```
cd ../external/JNAerator && mvn clean install && cd ../..
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Anarres JCPP (with JNAerator modifications)                        [jar]
[INFO] JNAerator Parent Project                                           [pom]
[INFO] OChafik's General Utilities                                        [jar]
[INFO] OChafik's Swing Utilities                                          [jar]
[INFO] JNAerator Runtime                                                  [jar]
[INFO] JNAerator Rococoa Runtime                                          [jar]
[INFO] JNAerator Parser                                                   [jar]
[INFO] JNAerator CLI and Studio Tools                                     [jar]
[INFO] JNAerator Maven Plugin                                    [maven-plugin]
[INFO] 
[INFO] ---------------< com.nativelibs4java:anarres-jnaerator >----------------
[INFO] Building Anarres JCPP (with JNAerator modifications) 1.2.10-SNAPSHOT [1/9]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ anarres-jnaerator ---
[INFO] Deleting /media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ anarres-jnaerator ---
[INFO] 
[INFO] --- maven-velocity-plugin:0.8:generate (default) @ anarres-jnaerator ---
[INFO] Velocity root path = /media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/src
[INFO] FileResourceLoader : adding path '/media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/src'
[INFO] Found 4 files in '/media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/src/main/velocity'...
[INFO] Got Maven properties : {maven-velocity-plugin.version=0.10-SNAPSHOT, mainClass=org.anarres.cpp.Main, shadedClassifierName=shaded, sonatypeOssDistMgmtSnapshotsUrl=https://oss.sonatype.org/content/repositories/snapshots/, shadedArtifactAttached=true, jnaerator.version=0.13-SNAPSHOT, project.build.sourceEncoding=UTF-8, bridj.version=0.7.1-SNAPSHOT, versionSpecificSubPackage=}
[INFO] Got properties : {bridj_version=0.7.1-SNAPSHOT, jna_version=null, jnaerator_version=0.13-SNAPSHOT, project_name=anarres-jnaerator, project_version=1.2.10-SNAPSHOT, rococoa_version=null, version=1.2.10-SNAPSHOT, versionSpecificSubPackage=null}
[INFO] Executing template 'Preprocessor.java'...
[INFO] Executing template 'Token.java'...
[INFO] Executing template 'Version.java'...
[INFO] Executing template 'Main.java'...
[INFO] Velocity root path = /media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/src
[INFO] FileResourceLoader : adding path '/media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/src'
[INFO] Found 0 files in '/media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/src/test/velocity'...
[INFO] Got Maven properties : {maven-velocity-plugin.version=0.10-SNAPSHOT, mainClass=org.anarres.cpp.Main, shadedClassifierName=shaded, sonatypeOssDistMgmtSnapshotsUrl=https://oss.sonatype.org/content/repositories/snapshots/, shadedArtifactAttached=true, jnaerator.version=0.13-SNAPSHOT, project.build.sourceEncoding=UTF-8, bridj.version=0.7.1-SNAPSHOT, versionSpecificSubPackage=}
[INFO] Got properties : {bridj_version=0.7.1-SNAPSHOT, jna_version=null, jnaerator_version=0.13-SNAPSHOT, project_name=anarres-jnaerator, project_version=1.2.10-SNAPSHOT, rococoa_version=null, version=1.2.10-SNAPSHOT, versionSpecificSubPackage=null}
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ anarres-jnaerator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] skip non existing resourceDirectory /media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/target/generated-resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ anarres-jnaerator ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 29 source files to /media/jigar/Data/project/fluidsynth-midi-service-j/external/JNAerator/anarres/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Anarres JCPP (with JNAerator modifications) 1.2.10-SNAPSHOT FAILURE [  1.436 s]
[INFO] JNAerator Parent Project 0.13-SNAPSHOT ............. SKIPPED
[INFO] OChafik's General Utilities 0.13-SNAPSHOT .......... SKIPPED
[INFO] OChafik's Swing Utilities 0.13-SNAPSHOT ............ SKIPPED
[INFO] JNAerator Runtime 0.13-SNAPSHOT .................... SKIPPED
[INFO] JNAerator Rococoa Runtime 0.13-SNAPSHOT ............ SKIPPED
[INFO] JNAerator Parser 0.13-SNAPSHOT ..................... SKIPPED
[INFO] JNAerator CLI and Studio Tools 0.13-SNAPSHOT ....... SKIPPED
[INFO] JNAerator Maven Plugin 0.13-SNAPSHOT ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.754 s
[INFO] Finished at: 2019-06-13T10:07:56+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project anarres-jnaerator: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Makefile:17: recipe for target '../external/JNAerator/jnaerator/target/jnaerator-0.13-SNAPSHOT-shaded.jar' failed
make: *** [../external/JNAerator/jnaerator/target/jnaerator-0.13-SNAPSHOT-shaded.jar] Error 1

```

**Comment by atsushieno** [comment]
My wild guess is the build failure is due to too new javac version:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project anarres-jnaerator: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] -> [Help 1]
```

I'm using openjdk 1.8.0_212 when building Android stuff.

This is what it would look when build passes: https://gist.github.com/atsushieno/c45ca0ae8049d16c78e06181f593ffde

**Comment by abhishekinexture** [comment]
After a successfull build, I run the  project and got the follwing error while clicking on Any of button available in the screen

```
2019-06-13 12:54:03.131 5113-5113/name.atsushieno.fluidsynthmidideviceservicej E/AndroidRuntime: FATAL EXCEPTION: main
    Process: name.atsushieno.fluidsynthmidideviceservicej, PID: 5113
    java.lang.UnsatisfiedLinkError: Unable to load library 'fluidsynth':
    dlopen failed: library "libfluidsynth.so" not found
    dlopen failed: library "libfluidsynth.so" not found
    dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/name.atsushieno.fluidsynthmidideviceservicej-Vd4uksWHJnu45jyeWAXJbw==/base.apk"],nativeLibraryDirectories=[/data/app/name.atsushieno.fluidsynthmidideviceservicej-Vd4uksWHJnu45jyeWAXJbw==/lib/x86, /data/app/name.atsushieno.fluidsynthmidideviceservicej-Vd4uksWHJnu45jyeWAXJbw==/base.apk!/lib/x86, /system/lib]]] couldn't find "libfluidsynth.so"
    Native library (android-x86/libfluidsynth.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:397)
        at fluidsynth.FluidsynthLibrary.<clinit>(FluidsynthLibrary.java:26)
        at fluidsynth.androidextensions.AndroidLogger.<clinit>(AndroidLogger.kt:10)
        at name.atsushieno.fluidsynthmidideviceservicej.FluidsynthMidiReceiver.<init>(FluidsynthMidiReceiver.kt:26)
        at name.atsushieno.fluidsynthmidideviceservicej.MainActivity$onCreate$1.onClick(MainActivity.kt:85)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libfluidsynth.so" not found
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 17 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libfluidsynth.so" not found
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 17 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/name.atsushieno.fluidsynthmidideviceservicej-Vd4uksWHJnu45jyeWAXJbw==/base.apk"],nativeLibraryDirectories=[/data/app/name.atsushieno.fluidsynthmidideviceservicej-Vd4uksWHJnu45jyeWAXJbw==/lib/x86, /data/app/name.atsushieno.fluidsynthmidideviceservicej-Vd4uksWHJnu45jyeWAXJbw==/base.apk!/lib/x86, /system/lib]]] couldn't find "libfluidsynth.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 17 more
    	Suppressed: java.io.IOException: Native library (android-x86/libfluidsynth.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
        		... 17 more
```

**Comment by abhishekinexture** [comment]
> My wild guess is the build failure is due to too new javac version:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project anarres-jnaerator: Compilation failure: Compilation failure: 
> [ERROR] Source option 5 is no longer supported. Use 6 or later.
> [ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
> [ERROR] -> [Help 1]
> ```
> 
> I'm using openjdk 1.8.0_212 when building Android stuff.
> 
> This is what it would look when build passes: https://gist.github.com/atsushieno/c45ca0ae8049d16c78e06181f593ffde

After changing this, I am able to run `make` command on the terminal.
Thank you

**Comment by atsushieno** [comment]
Building JNAerator and fluidsynthjna is only the first step among the entire build...!

You need libfuidsynth.so and all the native library dependencies for each ABI (arm64-v8a, armeabi-v7a, x86_64, and x86). That's what `make` build. It takes a lot more time.

Instead of building everything from source, you can download prebuilt binaries from https://github.com/atsushieno/fluidsynth-midi-service-j/issues/12 and put them under `(topdir)/fluidsynthjna/src/main/jniLibs/` (so that there are directories like `fluidsynthjna/src/main/jniLibs/x86_64` etc.)

**Comment by abhishekinexture** [comment]
> Building JNAerator and fluidsynthjna is only the first step among the entire build...!
> 
> You need libfuidsynth.so and all the native library dependencies for each ABI (arm64-v8a, armeabi-v7a, x86_64, and x86). That's what `make` build. It takes a lot more time.
> 
> Instead of building everything from source, you can download prebuilt binaries from #12 and put them under `(topdir)/fluidsynthjna/src/main/jniLibs/` (so that there are directories like `fluidsynthjna/src/main/jniLibs/x86_64` etc.)

Thanks for providing a link for native library dependencies for each platform. Now it's working fine.
